### ISSUE TITLE
project_registry fails to compile: RegistryError enum has discriminant 41 and 42 each assigned twice

### ISSUE THREAD

**Issue by abayomicornelius** [Heliobond/contracts#504]
## Overview

`project_registry/src/types.rs` does not compile at HEAD (`5f0c442`). The `RegistryError` enum (`#[contracterror]`, `#[repr(u32)]`) at lines 18-108 assigns the same discriminant value to two different variants, twice:

```rust
    // line 101
    InvalidStatusTransition = 41,
    // line 103
    ProjectStatusUnchanged = 42,
    // line 105
    CompactStorageTooLarge = 41,
    // line 107
    VotingPeriodTooLong = 42,
```

`InvalidStatusTransition` (line 101, added for #329) and `CompactStorageTooLarge` (line 105, added for #332) both claim discriminant `41`. `ProjectStatusUnchanged` (line 103, #329) and `VotingPeriodTooLong` (line 107, #332) both claim `42`. This is exactly the same class of bug as #311 (`VaultError` in `investment_vault`, already fixed), except it now exists independently in `RegistryError` and was never caught.

## Why it matters

This is not a lint — it's a hard compile error:

```
error[E0081]: discriminant value `41` assigned more than once
error[E0081]: discriminant value `42` assigned more than once
error: could not compile `project-registry` (lib) due to 2 previous errors
```

`cargo build`, `cargo test`, `cargo clippy`, and `stellar contract build` all fail immediately for the `project-registry` crate on a completely fresh clone of `main`. Since `investment_vault/src/lib.rs` cross-contract-imports `project_registry`'s compiled WASM, this also blocks building/testing `investment_vault` in any environment that hasn't already got a stale `project_registry.wasm` lying around. In short: the repository does not currently build. This has been silently broken since PR #468 (`#332` fixes) landed on top of PR #492 (`#329` fixes) without renumbering — confirmed by CI: the `ci.yml` push run on the current `main` HEAD (`5f0c442`) is red (`conclusion: failure`), and the daily scheduled "Network tests" workflow has failed every single day since at least 2026-09-08.

## Suggested fix

Renumber the two later-added variants to the next free discriminants (`43` and `44`):

```rust
    CompactStorageTooLarge = 43,
    VotingPeriodTooLong = 44,
```

Since the doc comment on the enum explicitly says "Variant values are stable — never reorder or renumber after deployment," prefer bumping the *new* (post-collision) variants rather than the older ones, to minimize disruption to anything that may already depend on `InvalidStatusTransition = 41` / `ProjectStatusUnchanged = 42`. Add a CI check (or a unit test asserting `size_of` / manual discriminant uniqueness) so this class of regression can't reach `main` silently again — see #311's sibling fix in `investment_vault` for precedent.
